# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_and_registration', '0004_user_wish_items'),
        ('wish_items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishitem',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='email_and_registration.User'),
            preserve_default=False,
        ),
    ]
