# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 19:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_and_registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hired_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
