# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_items', '0001_initial'),
        ('email_and_registration', '0003_auto_20170127_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wish_items',
            field=models.ManyToManyField(to='wish_items.WishItem'),
        ),
    ]
